# Generated by Django 6.1.1 on 2026-09-27 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Frontend brand key (agro, foods, prais, marketplace). Drives [data-brand].', max_length=40, unique=True)),
                ('slug', models.SlugField(help_text='URL slug under /companies.', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, help_text='Capsule step title.', max_length=60)),
                ('short_name_en', models.CharField(blank=True, help_text='Capsule step title.', max_length=60, null=True)),
                ('short_name_fr', models.CharField(blank=True, help_text='Capsule step title.', max_length=60, null=True)),
                ('short_name_sw', models.CharField(blank=True, help_text='Capsule step title.', max_length=60, null=True)),
                ('short_name_es', models.CharField(blank=True, help_text='Capsule step title.', max_length=60, null=True)),
                ('short_name_zh', models.CharField(blank=True, help_text='Capsule step title.', max_length=60, null=True)),
                ('short_name_pt', models.CharField(blank=True, help_text='Capsule step title.', max_length=60, null=True)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('role_en', models.CharField(blank=True, max_length=160, null=True)),
                ('role_fr', models.CharField(blank=True, max_length=160, null=True)),
                ('role_sw', models.CharField(blank=True, max_length=160, null=True)),
                ('role_es', models.CharField(blank=True, max_length=160, null=True)),
                ('role_zh', models.CharField(blank=True, max_length=160, null=True)),
                ('role_pt', models.CharField(blank=True, max_length=160, null=True)),
                ('summary', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True, null=True)),
                ('summary_fr', models.TextField(blank=True, null=True)),
                ('summary_sw', models.TextField(blank=True, null=True)),
                ('summary_es', models.TextField(blank=True, null=True)),
                ('summary_zh', models.TextField(blank=True, null=True)),
                ('summary_pt', models.TextField(blank=True, null=True)),
                ('step_body', models.TextField(blank=True)),
                ('step_body_en', models.TextField(blank=True, null=True)),
                ('step_body_fr', models.TextField(blank=True, null=True)),
                ('step_body_sw', models.TextField(blank=True, null=True)),
                ('step_body_es', models.TextField(blank=True, null=True)),
                ('step_body_zh', models.TextField(blank=True, null=True)),
                ('step_body_pt', models.TextField(blank=True, null=True)),
                ('signoff', models.CharField(default='A Mumita Company', max_length=80)),
                ('signoff_en', models.CharField(default='A Mumita Company', max_length=80, null=True)),
                ('signoff_fr', models.CharField(default='A Mumita Company', max_length=80, null=True)),
                ('signoff_sw', models.CharField(default='A Mumita Company', max_length=80, null=True)),
                ('signoff_es', models.CharField(default='A Mumita Company', max_length=80, null=True)),
                ('signoff_zh', models.CharField(default='A Mumita Company', max_length=80, null=True)),
                ('signoff_pt', models.CharField(default='A Mumita Company', max_length=80, null=True)),
                ('logo', models.FileField(blank=True, upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp'])])),
                ('palette_status', models.CharField(choices=[('approved', 'Approved'), ('provisional', 'Provisional')], default='provisional', max_length=12)),
                ('kind', models.CharField(choices=[('company', 'Company'), ('line', 'Product line')], default='company', max_length=10)),
                ('external_url', models.URLField(blank=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Set for product lines (LYDA and Mumi Chips sit under Mumita Foods).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='brands.brand')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
