# Generated by Django 6.1.1 on 2026-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=300)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, from Cloudflare.', max_length=2)),
                ('referrer_host', models.CharField(blank=True, max_length=120)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-views'],
                'constraints': [models.UniqueConstraint(fields=('date', 'path', 'country', 'referrer_host', 'device'), name='analytics_daily_visit_key')],
            },
        ),
    ]
