# Generated by Django 6.1.1 on 2026-09-28 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('realm', models.CharField(blank=True, choices=[('admin', 'Admin'), ('publisher', 'Publisher')], max_length=10)),
                ('username', models.CharField(help_text='The email address tried.', max_length=254)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('outcome', models.CharField(choices=[('success', 'Signed in'), ('bad_credentials', 'Wrong email or password'), ('wrong_realm', 'Right password, wrong sign-in page'), ('inactive', 'Account deactivated'), ('locked', 'Locked out')], max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_family', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, used as the article byline.', max_length=120)),
                ('must_change_password', models.BooleanField(default=True, help_text='Set for new accounts and after a reset; cleared by a password change.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
