# Generated by Django 6.1.1 on 2026-09-27 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(help_text='Email address or phone number.', max_length=254)),
                ('enquiry_type', models.CharField(choices=[('buy', 'Buy'), ('farm', 'Farm with us'), ('partner', 'Partner'), ('other', 'Other')], max_length=10)),
                ('message', models.TextField(max_length=2000)),
                ('contact_kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=5)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('page', models.CharField(blank=True, help_text='Referring page, from the Referer header.', max_length=300)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('closed', 'Closed')], db_index=True, default='new', max_length=10)),
                ('staff_notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('retention_until', models.DateField(db_index=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created'],
            },
        ),
    ]
