# Generated by Django 6.1.1 on 2026-09-28 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FORWARD = {'new': 'unread', 'assigned': 'read', 'closed': 'archived'}


def forwards(apps, schema_editor):
    Enquiry = apps.get_model('engagement', 'Enquiry')
    for old, new in FORWARD.items():
        Enquiry.objects.filter(status=old).update(status=new)


def backwards(apps, schema_editor):
    Enquiry = apps.get_model('engagement', 'Enquiry')
    for old, new in FORWARD.items():
        Enquiry.objects.filter(status=new).update(status=old)
    Enquiry.objects.filter(status='replied').update(status='closed')


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(blank=True, choices=[('contact', 'Contact'), ('partners', 'Partners'), ('join-distributor', 'Join: distributor'), ('join-strategic', 'Join: strategic partner'), ('join-investor', 'Join: investor'), ('join-volunteer', 'Join: volunteer'), ('join-grant', 'Join: grant'), ('marketplace-register', 'Marketplace registration'), ('feasibility', 'Feasibility study'), ('product-quote', 'Product quote'), ('service-quote', 'Service quote')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='topic',
            field=models.CharField(blank=True, help_text='E.g. the product the quote is for.', max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], db_index=True, default='unread', max_length=10),
        ),
        migrations.CreateModel(
            name='EnquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=10000)),
                ('emailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.enquiry')),
            ],
            options={
                'verbose_name_plural': 'enquiry replies',
                'ordering': ['created', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_or_place', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField(max_length=1000)),
                ('consent', models.BooleanField(default=False, help_text='The person agreed to have this published.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created', '-pk'],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
