"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlsplit

from .env import env_bool, env_int, env_list, env_str, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Optional .env next to manage.py (git-ignored). Real environment wins.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment so no key is ever committed. The fallback only
# applies with DEBUG on, so a production run without a key fails loudly.
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or (
    'django-insecure-local-dev-only' if DEBUG else None
)
if not SECRET_KEY:
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off')


ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]' if DEBUG else '')

# The public website (Next.js). Used for the revalidation webhook, links in
# emails and the list of "our" hosts when marking external links.
FRONTEND_URL = env_str('DJANGO_FRONTEND_URL', 'http://localhost:3111' if DEBUG else '').rstrip('/')

# The admin is the CMS. It never sits at the default /admin/ path.
ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL', 'cms-admin/').strip('/') + '/'
if ADMIN_URL == 'admin/':
    raise RuntimeError('DJANGO_ADMIN_URL must not be the default admin/ path')


# Application definition

INSTALLED_APPS = [
    # modeltranslation must precede django.contrib.admin.
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'axes',
    'accounts',
    'brands',
    'catalog',
    'content',
    'people',
    'engagement',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Static files (admin and DRF assets) straight from the app on Passenger.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'common.i18n.ApiLocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Axes last, per its docs.
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# DJANGO_DB_ENGINE picks the backend: sqlite (development default), mysql
# (Namecheap: MySQL/MariaDB through PyMySQL, pure Python, no compiler) or
# postgresql. For backward compatibility, DJANGO_DB_NAME alone selects
# PostgreSQL.

DB_ENGINE = env_str('DJANGO_DB_ENGINE', 'postgresql' if os.environ.get('DJANGO_DB_NAME') else 'sqlite').lower()

if DB_ENGINE == 'mysql':
    try:
        import pymysql
    except ImportError:  # pragma: no cover - only without the dependency
        pass
    else:
        # Django checks the mysqlclient version; PyMySQL implements the same
        # DB-API, so report a compatible version before installing the shim.
        pymysql.version_info = (2, 2, 1, 'final', 0)
        pymysql.install_as_MySQLdb()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env_str('DJANGO_DB_NAME'),
            'USER': env_str('DJANGO_DB_USER'),
            'PASSWORD': env_str('DJANGO_DB_PASSWORD'),
            'HOST': env_str('DJANGO_DB_HOST', 'localhost'),
            'PORT': env_str('DJANGO_DB_PORT', '3306'),
            'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', 0),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'isolation_level': 'read committed',
            },
            'TEST': {'CHARSET': 'utf8mb4', 'COLLATION': 'utf8mb4_unicode_ci'},
        }
    }
elif DB_ENGINE in ('postgresql', 'postgres'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env_str('DJANGO_DB_NAME'),
            'USER': env_str('DJANGO_DB_USER'),
            'PASSWORD': env_str('DJANGO_DB_PASSWORD'),
            'HOST': env_str('DJANGO_DB_HOST', 'localhost'),
            'PORT': env_str('DJANGO_DB_PORT', '5432'),
            'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', 60),
        }
    }
elif DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(env_str('DJANGO_SQLITE_PATH') or BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    raise RuntimeError('DJANGO_DB_ENGINE must be mysql, postgresql or sqlite')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication
# Review §11: strong passwords on every admin account; login throttling via
# django-axes (5 failures per username+IP, 1 hour lock-out).

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 12}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

if len(sys.argv) > 1 and sys.argv[1] == 'test':
    # Fast hashing for the test suite only.
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = env_int('AXES_FAILURE_LIMIT', 5)
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_CALLABLE = 'accounts.auth.lockout_response'
# Client IP for throttling, axes and the IP hashes (common/security.py).
# Nothing is trusted by default: REMOTE_ADDR is used.
# DJANGO_NUM_PROXIES: proxies of our own hosting that append to
#   X-Forwarded-For (DRF semantics: the n-th address from the right).
# DJANGO_TRUSTED_PROXY_KEY / DJANGO_TRUSTED_PROXIES: a request with
#   X-Proxy-Key equal to the key, or from those IPs/CIDRs, is the frontend
#   Worker; the first hop of DJANGO_TRUSTED_PROXY_HEADER is the visitor.
NUM_PROXIES = env_int('DJANGO_NUM_PROXIES', 0)
TRUSTED_PROXY_KEY = env_str('DJANGO_TRUSTED_PROXY_KEY')
TRUSTED_PROXIES = env_list('DJANGO_TRUSTED_PROXIES')
TRUSTED_PROXY_HEADER = env_str('DJANGO_TRUSTED_PROXY_HEADER', 'X-Forwarded-For')
AXES_CLIENT_IP_CALLABLE = 'common.security.client_ip'


# Internationalisation
# Six site locales, using the frontend's codes (src/i18n/locales.ts).
# Translatable model fields use django-modeltranslation: one column per
# locale (title_en, title_fr, ...), English as the fallback.

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('sw', 'Kiswahili'),
    ('es', 'Español'),
    ('zh', '中文'),
    ('pt', 'Português'),
]
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en',)

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static and uploaded files
# MEDIA_ROOT sits outside any web root the frontend serves (Review §11).
# Static files are served by WhiteNoise. Uploaded media is served by Apache
# when MEDIA_ROOT is inside the subdomain's document root (see README), or by
# Django itself with DJANGO_SERVE_MEDIA=1.

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles'))
MEDIA_URL = '/' + os.environ.get('DJANGO_MEDIA_URL', '/media/').strip('/') + '/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))
# Absolute origin that media URLs in API responses start with, e.g.
# https://api.mumitaholdings.com. Empty: built from the request host.
MEDIA_BASE_URL = env_str('DJANGO_MEDIA_BASE_URL').rstrip('/')
SERVE_MEDIA = env_bool('DJANGO_SERVE_MEDIA', DEBUG)
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
# Bodies above this are spooled to a temp file rather than held in memory.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
# Non-file request data (JSON bodies, form fields) is capped at 2 MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
# Image uploads (gallery, article images): 15 MB, jpg/png/webp/heic.
IMAGE_UPLOAD_MAX_BYTES = env_int('IMAGE_UPLOAD_MAX_BYTES', 15 * 1024 * 1024)
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755


# REST framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer']
    + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'enquiries': os.environ.get('ENQUIRY_THROTTLE_RATE', '5/hour'),
        'testimonials': os.environ.get('TESTIMONIAL_THROTTLE_RATE', '3/hour'),
        'login': os.environ.get('LOGIN_THROTTLE_RATE', '30/hour'),
    },
    # 0 means REMOTE_ADDR (DRF's None would trust the whole X-Forwarded-For).
    'NUM_PROXIES': NUM_PROXIES,
}

# Cache backs the throttle counters. Use a shared cache (Redis/Memcached)
# when running more than one process in production.
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}


# CORS: only the frontend origin(s) may call the API from a browser, with
# credentials (the dashboards use the session cookie).

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:3111' if DEBUG else ''
)
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST']
CORS_ALLOW_CREDENTIALS = True

# CSRF: the frontend origins are trusted for unsafe requests (the dashboards
# send X-CSRFToken), plus anything listed explicitly (the API's own origin
# for the Django admin behind a proxy).
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(env_list('DJANGO_CSRF_TRUSTED_ORIGINS') + CORS_ALLOWED_ORIGINS))
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
# The dashboards read the token from GET auth/csrf/ (body) or the cookie.
CSRF_COOKIE_HTTPONLY = False


# Keys shared with the frontend Worker (never committed; see .env.example).
REVALIDATE_KEY = env_str('REVALIDATE_KEY')
REVALIDATE_TIMEOUT = float(env_str('REVALIDATE_TIMEOUT', '3'))
ANALYTICS_INGEST_KEY = env_str('ANALYTICS_INGEST_KEY')

# Hosts treated as "ours" when deciding whether a link in an article is
# external (external links get rel="noopener noreferrer").
SITE_HOSTS = env_list('DJANGO_SITE_HOSTS', 'mumitaholdings.com')
if FRONTEND_URL:
    SITE_HOSTS.append(urlsplit(FRONTEND_URL).hostname or '')


# Enquiries

ENQUIRY_NOTIFY_EMAILS = env_list('ENQUIRY_NOTIFY_EMAILS', 'info@localhost' if DEBUG else '')
ENQUIRY_RETENTION_DAYS = env_int('ENQUIRY_RETENTION_DAYS', 365)

# Accounts: new dashboard accounts must use the company domain.
ACCOUNT_EMAIL_DOMAIN = env_str('ACCOUNT_EMAIL_DOMAIN', 'mumitaholdings.com').lower().lstrip('@')


# Email
# Console backend unless DJANGO_EMAIL_HOST is set, then SMTP.

DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'website@localhost')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
if os.environ.get('DJANGO_EMAIL_HOST'):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.environ['DJANGO_EMAIL_HOST'],
                'port': env_int('DJANGO_EMAIL_PORT', 587),
                'username': os.environ.get('DJANGO_EMAIL_USER', ''),
                'password': os.environ.get('DJANGO_EMAIL_PASSWORD', ''),
                'use_tls': env_bool('DJANGO_EMAIL_USE_TLS', True),
                'timeout': 10,
            },
        },
    }
else:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.console.EmailBackend'}}


# Security
# Review §11 / PLAN §0.2. Always-on headers first, then HTTPS-only settings
# that apply whenever DEBUG is off.

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
# Sessions: 8 h idle timeout (the expiry slides on every request).
# In production the cookies are shared by mumitaholdings.com and
# api.mumitaholdings.com via DJANGO_COOKIE_DOMAIN=.mumitaholdings.com.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_SAVE_EVERY_REQUEST = True
CSRF_COOKIE_SAMESITE = 'Lax'
COOKIE_DOMAIN = env_str('DJANGO_COOKIE_DOMAIN') or None
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN

# CSP for everything Django itself serves (admin and JSON). The public site's
# CSP is set by the Next.js frontend.
from django.utils.csp import CSP  # noqa: E402

SECURE_CSP = {
    'default-src': [CSP.SELF],
    'script-src': [CSP.SELF],
    'style-src': [CSP.SELF],
    'img-src': [CSP.SELF, 'data:'],
    'font-src': [CSP.SELF],
    'connect-src': [CSP.SELF],
    'object-src': [CSP.NONE],
    'base-uri': [CSP.SELF],
    'form-action': [CSP.SELF],
    'frame-ancestors': [CSP.NONE],
}

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = env_int('DJANGO_HSTS_SECONDS', 60 * 60 * 24 * 365)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('DJANGO_HSTS_PRELOAD', False)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Behind Cloudflare / a TLS-terminating proxy, trust its scheme header.
    if env_bool('DJANGO_BEHIND_PROXY', False):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    if not ALLOWED_HOSTS:
        raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG is off')


# Logging
# Never log enquiry bodies or contact details: application loggers record
# ids and types only. Mail and request errors go to stderr.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {'plain': {'format': '%(asctime)s %(levelname)s %(name)s %(message)s'}},
    'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        'engagement': {'handlers': ['console'], 'level': os.environ.get('ENQUIRY_LOG_LEVEL', 'INFO'), 'propagate': False},
        'accounts': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'content': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'common': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}
