# Generated by Django 6.1.1 on 2026-09-27 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tier', models.CharField(choices=[('institutional', 'Development and institutional'), ('buyer', 'Buyers and distribution')], max_length=14)),
                ('logo', models.FileField(blank=True, help_text="The partner's own mark. Monochrome treatment is applied by the frontend.", upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp'])])),
                ('url', models.URLField(blank=True)),
                ('relationship', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240)),
                ('relationship_en', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240, null=True)),
                ('relationship_fr', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240, null=True)),
                ('relationship_sw', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240, null=True)),
                ('relationship_es', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240, null=True)),
                ('relationship_zh', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240, null=True)),
                ('relationship_pt', models.CharField(blank=True, help_text='The real relationship: award, grant, programme, stockist.', max_length=240, null=True)),
                ('since_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('permission_to_display', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Frontend region key.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60, null=True)),
                ('name_fr', models.CharField(max_length=60, null=True)),
                ('name_sw', models.CharField(max_length=60, null=True)),
                ('name_es', models.CharField(max_length=60, null=True)),
                ('name_zh', models.CharField(max_length=60, null=True)),
                ('name_pt', models.CharField(max_length=60, null=True)),
                ('note', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25)),
                ('note_en', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25, null=True)),
                ('note_fr', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25, null=True)),
                ('note_sw', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25, null=True)),
                ('note_es', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25, null=True)),
                ('note_zh', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25, null=True)),
                ('note_pt', models.CharField(blank=True, help_text='Map pin label, 25 characters maximum.', max_length=25, null=True)),
                ('geo_key', models.CharField(help_text='Region name in the frontend map geometry.', max_length=60)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('qualification', models.CharField(blank=True, help_text='Highest qualification.', max_length=160)),
                ('qualification_en', models.CharField(blank=True, help_text='Highest qualification.', max_length=160, null=True)),
                ('qualification_fr', models.CharField(blank=True, help_text='Highest qualification.', max_length=160, null=True)),
                ('qualification_sw', models.CharField(blank=True, help_text='Highest qualification.', max_length=160, null=True)),
                ('qualification_es', models.CharField(blank=True, help_text='Highest qualification.', max_length=160, null=True)),
                ('qualification_zh', models.CharField(blank=True, help_text='Highest qualification.', max_length=160, null=True)),
                ('qualification_pt', models.CharField(blank=True, help_text='Highest qualification.', max_length=160, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(70)])),
                ('department', models.CharField(choices=[('agric-consultancy', 'Agric Consultancy'), ('food-processing', 'Food Processing'), ('nutrition', 'Nutrition'), ('it', 'IT'), ('hr', 'HR')], max_length=20)),
                ('tier', models.CharField(choices=[('executive', 'Executive'), ('advisory', 'Advisory board'), ('mentor', 'Mentor'), ('operations', 'Operations')], default='operations', max_length=12)),
                ('value_statement', models.TextField(blank=True, help_text='Two or three sentences.')),
                ('value_statement_en', models.TextField(blank=True, help_text='Two or three sentences.', null=True)),
                ('value_statement_fr', models.TextField(blank=True, help_text='Two or three sentences.', null=True)),
                ('value_statement_sw', models.TextField(blank=True, help_text='Two or three sentences.', null=True)),
                ('value_statement_es', models.TextField(blank=True, help_text='Two or three sentences.', null=True)),
                ('value_statement_zh', models.TextField(blank=True, help_text='Two or three sentences.', null=True)),
                ('value_statement_pt', models.TextField(blank=True, help_text='Two or three sentences.', null=True)),
                ('consent_to_publish', models.BooleanField(default=False, help_text='Written consent received. Required before the profile is shown.')),
                ('is_blog_author', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
