# Generated by Django 6.1.1 on 2026-09-27 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('media_key', models.CharField(help_text='Frontend media-manifest id.', max_length=120)),
                ('alt', models.CharField(max_length=200)),
                ('alt_en', models.CharField(max_length=200, null=True)),
                ('alt_fr', models.CharField(max_length=200, null=True)),
                ('alt_sw', models.CharField(max_length=200, null=True)),
                ('alt_es', models.CharField(max_length=200, null=True)),
                ('alt_zh', models.CharField(max_length=200, null=True)),
                ('alt_pt', models.CharField(max_length=200, null=True)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('caption_en', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_fr', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_sw', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_es', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_zh', models.CharField(blank=True, max_length=240, null=True)),
                ('caption_pt', models.CharField(blank=True, max_length=240, null=True)),
                ('category', models.SlugField(blank=True, max_length=40)),
                ('place', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('has_identifiable_faces', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_sw', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_zh', models.CharField(max_length=200, null=True)),
                ('title_pt', models.CharField(max_length=200, null=True)),
                ('dek', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300)),
                ('dek_en', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300, null=True)),
                ('dek_fr', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300, null=True)),
                ('dek_sw', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300, null=True)),
                ('dek_es', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300, null=True)),
                ('dek_zh', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300, null=True)),
                ('dek_pt', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300, null=True)),
                ('body', models.TextField(help_text='Markdown.')),
                ('body_en', models.TextField(help_text='Markdown.', null=True)),
                ('body_fr', models.TextField(help_text='Markdown.', null=True)),
                ('body_sw', models.TextField(help_text='Markdown.', null=True)),
                ('body_es', models.TextField(help_text='Markdown.', null=True)),
                ('body_zh', models.TextField(help_text='Markdown.', null=True)),
                ('body_pt', models.TextField(help_text='Markdown.', null=True)),
                ('lens', models.CharField(blank=True, choices=[('hr', 'HR'), ('agric-economics', 'Agric-economics'), ('nutrition', 'Nutrition'), ('food-processing', 'Food processing'), ('it', 'IT')], max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='True original publication date.', null=True)),
                ('media_key', models.CharField(blank=True, help_text='Hero image media-manifest id.', max_length=120)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_fr', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_sw', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_es', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_zh', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_pt', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_fr', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_sw', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_es', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_zh', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description_pt', models.CharField(blank=True, max_length=160, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='people.teammember')),
            ],
            options={
                'ordering': ['-published_at', '-pk'],
            },
        ),
    ]
