# Generated by Django 6.1.1 on 2026-09-28 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    apps.get_model('content', 'Post').objects.filter(status='review').update(status='pending_review')


def backwards(apps, schema_editor):
    Post = apps.get_model('content', 'Post')
    Post.objects.filter(status__in=['pending_review', 'changes_requested']).update(status='review')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_meta_description'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='byline',
            field=models.CharField(blank=True, help_text='Public author name. Empty: the owner\'s name, else "Mumita Holdings".', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The account that owns the article (publishers see only their own).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_es',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_fr',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_pt',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_sw',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_zh',
            field=models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='review_note',
            field=models.TextField(blank=True, help_text='Shown to the author when changes are requested.'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('farms', 'Farms'), ('training', 'Training'), ('processing', 'Processing'), ('cold', 'Cold rooms'), ('products', 'Products'), ('events', 'Events'), ('awards', 'Awards'), ('csr', 'Community'), ('international', 'International'), ('prais', 'Praïs')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_key',
            field=models.CharField(blank=True, help_text='Frontend media-manifest id.', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Optional specialist profile (lens byline).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='people.teammember'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_es',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_fr',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_pt',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_sw',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_zh',
            field=models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_key',
            field=models.CharField(blank=True, help_text='Frontend media-manifest id of the hero, for posts without a cover.', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('changes_requested', 'Changes requested'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gallery', 'Gallery photo'), ('inline', 'Article image')], default='inline', max_length=10)),
                ('file', models.FileField(max_length=200, upload_to='uploads/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('renditions', models.JSONField(default=list, help_text='[{"w", "fmt", "path"}], paths relative to MEDIA_ROOT.')),
                ('blur', models.TextField(blank=True, help_text='A tiny WebP data URI for the loading placeholder.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='content.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.image'),
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('dek', models.CharField(blank=True, help_text='Standfirst under the title.', max_length=300)),
                ('excerpt', models.CharField(blank=True, help_text='Card text. Computed from the body when empty.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='HTML, sanitized on save to the article allow-list.')),
                ('lens', models.CharField(blank=True, choices=[('hr', 'HR'), ('agric-economics', 'Agric-economics'), ('nutrition', 'Nutrition'), ('food-processing', 'Food processing'), ('it', 'IT')], max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('changes_requested', 'Changes requested')], default='pending_review', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='content.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
