# Generated by Django 6.1.1 on 2026-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_dashboard_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendRebuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'frontend rebuild',
            },
        ),
    ]
